services:
  geti-bot:
    build: .
    container_name: geti-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - geti-bot-net

networks:
  geti-bot-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
